drop table if exists PRODUCER;
drop table if exists PRODUCT;

create table PRODUCER
(
    ID   bigint generated by default as identity,
    NAME varchar(255) not null unique,
    primary key (ID)
);

create table PRODUCT
(
    ID          bigint generated by default as identity,
    PRODUCER_ID bigint          not null,
    NAME        varchar(255) not null unique,
    primary key (ID),
    foreign key (PRODUCER_ID) references PRODUCER (ID)
);